baseURL = 'https://stagebackoffice.github.io/'
languageCode = 'pt-pt'
title = 'stagebackoffice.pt'
theme = 'ananke'
# --------------------------------------------------------
DefaultContentLanguage = "pt"
SectionPagesMenu = "main"

[languages]
  [languages.pt]
    title = "stagebackoffice"
    weight = 1
    contentDir = "content/pt"

# ------------------------------------------------

googleAnalytics = "G-QJ47W24DHK"
# ------------------------------------------------
# ------------------------------------------------
[params]
  text_color = ""

  # author = "Ricardo Almeida"
  author = ""

  favicon = ""
  site_logo = ""
  description = "projeto stagebackoffice"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  recent_posts_number = 3

# ------------------------------------------------

pluralizelisttitles = false

# ------------------------------------------------