baseURL = 'https://stagebackoffice.github.io/'
languageCode = 'pt-pt'
title = 'stagebackoffice.pt'
theme = 'ananke'
# --------------------------------------------------------
DefaultContentLanguage = "pt"

[languages]
  [languages.pt]
    title = "stagebackoffice"
    weight = 1
    contentDir = "content/pt"
# --------------------------------------------------------
#SectionPagesMenu = "main"

[menu]
[[menu.main]]
  identifier = "proj"
  name = 'Projeto'
  pageRef = '/projeto'
  weight = 10
[[menu.main]]
  identifier = "palco"
  name = 'Palco'
  url = '/projeto/palco'
  parent = "proj"
  weight = 1
[[menu.main]]
  identifier = "montagem"  
  name = 'Montagem'
  url = '/projeto/montagem'
  parent = "proj"
  weight = 2
[[menu.main]]
  identifier = "pubs"
  name = 'Publicações'
  pageRef = "/pubs"
  weight = 30
[[menu.main]]
  identifier = "at"
  name = "Área Técnica"
  pageRef = "/at"
  weight = 60
[[menu.main]]
  identifier = "lingua"
  name = "Calão"
  pageRef = "/at/linguagem-técnica"
  parent = "at"
  weight = 1

# ------------------------------------------------

googleAnalytics = "G-QJ47W24DHK"
# ------------------------------------------------
# ------------------------------------------------
[params]
  text_color = ""

  # author = "Ricardo Almeida"
  author = ""

  favicon = ""
  site_logo = ""
  description = "projeto stagebackoffice"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  recent_posts_number = 3
  date_format = "2 January 2006"

# ------------------------------------------------
pluralizelisttitles = false

# ------------------------------------------------
[[params.ananke_socials]]
name = "github"
url = "https://github.com/stagebackoffice"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/stagebackoffice/"

# ------------------------------------------------
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"


# ------------------------------------------------
  [markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

# ------------------------------------------------
# ------------------------------------------------
